### ISSUE TITLE
Two things not working : Renewing Map config.json and Unassigning Skillpoints Function

### ISSUE THREAD

**Issue by yirahdream** [shalzuth/D2RModding#12]
hey thank you for your work, lots of people are enjoying it.

this is my config.json

{
   "enableLadderRunewords": true,
  "showItemLevels": true,
  "enableStatUnassignment": true,
  "enableUberQuest": true,
  "enableOfflineWorldEvent": true,
  "enableMultipleHirelings": false,
  "alwaysDisplayLifeAndManaValues": true,
  "enableSkillUnassignment": true,
  "alwaysRegenMapInSP": true
}

RegenmapinSP doesn't work properly. For 3 or 4 times it does, but then after that the maps keep overlapping each other.
I do not know why it happens not in the first place but after 3 or 4 games.. I keep only doing Andy Runs and after 3 or 4 games I have to manually erase the map files from the saved games folder.
enableSkillUnassignment does not work at all.

P.S. Sometimes the game crashes when I am in Act2, not very often but sometimes.

Thank you.

**Comment by Mownan** [comment]
Sorry to jump on your question mate, but I have one of my own. How does one go about adding those commands? is that added during compiling or can I add to precompiled if so how and where? 

Cheers in advance.

**Comment by yirahdream** [comment]
> in

you can config it in the D2R folder, the file's name is config.json open it with notepad or note++, any text editor 😁

**Comment by Mownan** [comment]
Thanks mate, much obliged.
