### ISSUE TITLE
How to unassignment stat and skill points?

### ISSUE THREAD

**Issue by chenyu8674** [shalzuth/D2RModding#19]
Already add
"enableStatUnassignment": true,
"enableSkillUnassignment": true,
in config.json

But in game, can't find where to unassignment points.

**Comment by ChaosMarc** [comment]
enableStatUnassignment works. you just have to press ALT and click on the button to assign points to unassign them. I haven't tested enableSkillUnassignment yet so I can't say anything about that.

**Comment by shalzuth** [comment]
enableSkillUnassignment doesn't work atm
