### ISSUE TITLE
Game Shuts down during opening cinematics

### ISSUE THREAD

**Issue by blazinz00t** [shalzuth/D2RModding#2]
Hi Shalzuth, 
is there somthing i have done wrong? i have downloaded the installer and your modding.exe they are both in the same directory as game.exe every time i try to play (including as admin) the game starts to loads the opening cinematics then just closes every time. any possible solution?

**Comment by csuhta** [comment]
I’ve noticed that you need to either be playing full screen or maximize your game window while the intro movies are running. That prevents a crash when you get to the character screen. Once you get to the character screen you can then put your window back the way you like it.

**Comment by Blindmikey** [comment]
I'm getting this same issue. Event log shows:

```Faulting application name: D2RModding.exe, version: 1.0.0.0, time stamp: 0xb5ba78d8
Faulting module name: clr.dll, version: 4.8.4341.0, time stamp: 0x602301f3
Exception code: 0xc0000005
Fault offset: 0x000000000048e49d
Faulting process id: 0x6958
Faulting application start time: 0x01d7330338116b91
Faulting application path: F:\Program Files (x86)\Blizzard\D2R Technical Alpha\D2RModding.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report Id: 9436f26b-1294-4fa0-bbee-65931f9e73a4
Faulting package full name: 
Faulting package-relative application ID: 
```

and

```Application: D2RModding.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FF889BAE49D (00007FF889720000) with exit code 80131506.
```

**Comment by shalzuth** [comment]
I pushed a change that should help with this - https://github.com/shalzuth/D2RModding/releases/download/1.0.1/D2RModding.exe
