### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by Erehr** [shalzuth/D2RModding#22]
After accidentally removing previous game folder and trying to download the game again I'm getting the following error:

Unhandled Exception: System.IO.FileNotFoundException: invalid archive directory
   at TACTLib.Client.ClientHandler..ctor(String basePath, ClientCreateArgs createArgs)
   at D2RModding.Program.Main(String[] args)

or this one

Unhandled Exception: System.NotImplementedException: unable to detect product. ensure that the archive directory is correct
   at TACTLib.ProductHelpers.ProductFromLocalInstall(String path)
   at TACTLib.Client.ClientHandler..ctor(String basePath, ClientCreateArgs createArgs)
   at D2RModding.Program.Main(String[] args)

No matter which version. Running as admin didn't make a difference. Even downloaded all game files from another source but that didn't help either.

**Comment by Bucker69** [comment]
Did you try to download back with https://github.com/barncastle/Battle.Net-Installer/tree/v1.5

After do one of these command line cmd.exe to start the download

BNetInstaller.exe --prod osib --uid osi_beta --lang enus --dir "c:\D2R Technical Alpha"
BNetInstaller.exe --prod osib --lang enus --dir "c:\D2R Technical Alpha"

After put D2RModding.exe in same folder that the game is.

**Comment by Erehr** [comment]
Reinstalling battle.net worked.
