### ISSUE TITLE
Cant find the D2rModded.exe

### ISSUE THREAD

**Issue by Captain121** [shalzuth/D2RModding#3]
Hi this might be a very dumb question but i cant find the .exe anywhere in the dowloaded files.

**Comment by shalzuth** [comment]
https://github.com/shalzuth/D2RModding/releases/download/1.0.0/D2RModding.exe

**Comment by Captain121** [comment]
thank you very much for the speedy reply. I got it going like 5 mins ago used visual studio to make exe. Learned a new skill today :D
