### ISSUE TITLE
Closing on Open

### ISSUE THREAD

**Issue by n0vares** [shalzuth/D2RModding#5]
Greetings shalzuth, 

Thanks for your efforts with this. It's much appreciated. I had a quick question for you: although this problem is not my own and your project works for me flawlessly - there have been two people that I've tried to help get this working. After they get the game installed and everything is the way it should be, even using the exe that I compiled myself for them vs the one that you posted as a fix, and various others - upon attempting to load the game it just instantly closes. D2r starts to open and then closes again. It doesn't matter how many times you try it it will always close. 

Do you have any insight into this? 

Thank you!

**Comment by shalzuth** [comment]
I think it's a timing issue... try again, or recompile with https://github.com/shalzuth/D2RModding/blob/main/D2RModding/Program.cs#L139 this timeout set to 150 (for 1.5s) or 200 (for 2s)
