### ISSUE TITLE
Where is exe ? cannot see it in the source code 

### ISSUE THREAD

**Issue by karocksjoelee** [shalzuth/D2RModding#8]
As titled, anything I missed?

**Comment by rbasniak** [comment]
There's no binary distribution. You need to compile it to build the exe file.

Download the free version of Visual Studio from https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&rel=16 and just click the Build menu, Rebuild Solution.

**Comment by ChaosMarc** [comment]
Why not use the pre-compiled releases? https://github.com/shalzuth/D2RModding/releases

**Comment by karocksjoelee** [comment]
Got it
