### ISSUE TITLE
Color of Uniques and Questitems whil using Gamepad

### ISSUE THREAD

**Issue by gittegumba** [shalzuth/D2RModding#9]
Hi :)

Uniques have white colored text if i use a gamepad...

If i use mouse and keyboard its golden like it should be ...

how can i fix this ?

thank you in advance

**Comment by shalzuth** [comment]
Seems like a blizz bug, but not sure. I'll keep this open if anyone has a solution.

**Comment by deadjack133** [comment]
if found how to fix it:
In file \Data\global\ui\Layouts\controller\_profilehd.json
change two strings
from
"QuestColor": "$FontColorLightGold",
"UniqueColor": "$FontColorLightGold",
to
"QuestColor": "$FontColorGoldYellow",
"UniqueColor": "$FontColorGoldYellow",

**Comment by gittegumba** [comment]
> 
> 
> i found how to fix it:
> In file \Data\global\ui\Layouts\controller\ _profilehd.json
> change two strings in block named "TooltipStylePC"
> from
> "QuestColor": "$FontColorLightGold",
> "UniqueColor": "$FontColorLightGold",
> to
> "QuestColor": "$FontColorGoldYellow",
> "UniqueColor": "$FontColorGoldYellow",

awesome :D

**Comment by gittegumba** [comment]
but there still is a problm ... lol
i dont have a "controller" folder in \Data\global\ui\Layouts\ ....

**Comment by deadjack133** [comment]
> but there still is a problm ... lol
> i dont have a "controller" folder in \Data\global\ui\Layouts\ ....

First you need to unpack this file using
http://www.zezula.net/en/casc/main.html

**Comment by gittegumba** [comment]
D2R Technical Alpha\Data\global\ui\Layouts\controller\_profilehd.json

i unpacked only this file and edited it ...

but uniques are still white with controller

do i have to force D2R to load it instad of the compressed file ?

**Comment by gittegumba** [comment]
works now :)

i had to change it in : _profilehd.json and _profilelv.json 

thx again :)

**Comment by deadjack133** [comment]
mmm! maybe my file fix it only in HD mode, didn't test it in legacy

**Comment by gittegumba** [comment]
I use HD mode maybe its becouse of ultrawide or so ? ... lol dunno

**Comment by deadjack133** [comment]
Hi @shalzuth ! Thank you for this tool. Can you please add this fix in next version, if it possible of course? And maybe another from my issue about targeting with controller

**Comment by Nekromanyonec** [comment]
#

> Hi @shalzuth ! Thank you for this tool. Can you please add this fix in next version, if it possible of course? And maybe another from my issue about targeting with controller

This does not work. Made an extraction of 30GB game archives from the Data, tried different variations of the paths, he basically does not read them, continues to read from the encrypted data archives. The utility itself, using your link, does not allow you to change the files in the archive, there is no such function. So it's not clear what to do in this case.

**Comment by deadjack133** [comment]
> > Hi @shalzuth ! Thank you for this tool. Can you please add this fix in next version, if it possible of course? And maybe another from my issue about targeting with controller
> 
> This does not work. Made an extraction of 30GB game archives from the Data, tried different variations of the paths, he basically does not read them, continues to read from the encrypted data archives. The utility itself, using your link, does not allow you to change the files in the archive, there is no such function. So it's not clear what to do in this case.

You doing something wrong, even class unlock in D2RModding implements with this metod (files in \Data\global\ui\Layouts), so if you can play as any clas, then your game atleast read file  \Data\global\ui\Layouts\CharacterCreatePanelHD.json.

And, just in case, you use D2RModding or D2R-OFFLINE? Because i test it only with D2RModding

**Comment by Nekromanyonec** [comment]
> > > Hi @shalzuth ! Thank you for this tool. Can you please add this fix in next version, if it possible of course? And maybe another from my issue about targeting with controller
> > 
> > 
> > This does not work. Made an extraction of 30GB game archives from the Data, tried different variations of the paths, he basically does not read them, continues to read from the encrypted data archives. The utility itself, using your link, does not allow you to change the files in the archive, there is no such function. So it's not clear what to do in this case.
> 
> You doing something wrong, even class unlock in D2RModding implemented with this method (files in \Data\global\ui\Layouts), so if you can play as any class, then your game atleast read file \Data\global\ui\Layouts\CharacterCreatePanelHD.json.
> 
> And, just in case, you use D2RModding or D2R-OFFLINE? Because i test it only with D2RModding

I use Ferib Offline, because its stable work and dont close game, and i can play single without IT\CP(create).

**Comment by shalzuth** [comment]
@Nekromanyonec D2RModding is stable and don't close game. Also doesn't modify the save files. If there's an issue with it, open an issue and I can try to help.
Fixed with https://github.com/shalzuth/D2RModding/commit/bf2ebf10782951b6ccc1a989104eed6b389289fc
